#!/bin/bash

if [ $# -lt 1 ]; then
    echo "Usage: $0 <dir>"
    exit
fi

export sootcp=$PLINY_SOOT_HOME/lib/soot-trunk.jar
export sootcp=$sootcp:$PLINY_SOOT_HOME/lib/jasminclasses-2.5.0.jar
export sootcp=$sootcp:$PLINY_SOOT_HOME/lib/polyglot.jar
export sootcp=$sootcp:$PLINY_SOOT_HOME/lib/java_cup.jar
export sootcp=$sootcp:$JAVA_HOME/jre/lib/rt.jar
export sootcp=$sootcp:$JAVA_HOME/jre/lib/jce.jar

export androidcp=$ANDROID_HOME/platforms/android-20/android.jar
export androidcp=$androidcp:$ANDROID_HOME/extras/android/support/v4/android-support-v4.jar

sootargs="-cp $sootcp:$androidcp:$1 -allow-phantom-refs -keep-line-number"
java -ea -Xss50m -cp $sootcp:$PLINY_SOOT_HOME/classes pliny_soot.Driver $sootargs -process-dir $1 ${*:2}
